export class Log {
  _id:string;
  ticket:string;
  uploader:string;
  androidVersion:string;
  versionCode:string;
  versionName:string;
  deviceId:string;
  installationId:string;
  isSilent:boolean;
  logCat:string;
  packageName:string;
  phoneModel:string;
  phoneBrand:string;
  reportId:string;
  stackTrace:string;
  userIp:string;
  createdAt:Date;
  updatedAt:Date;
}
